// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: github.com/ashleywang1/capture-the-flag-apiserver/api/apiserver.proto

package api

import (
	context "context"
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/solo-io/protoc-gen-ext/extproto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Flag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag string `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *Flag) Reset() {
	*x = Flag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_rawDescGZIP(), []int{0}
}

func (x *Flag) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

type CaptureTheFlagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CaptureTheFlagRequest) Reset() {
	*x = CaptureTheFlagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureTheFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureTheFlagRequest) ProtoMessage() {}

func (x *CaptureTheFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureTheFlagRequest.ProtoReflect.Descriptor instead.
func (*CaptureTheFlagRequest) Descriptor() ([]byte, []int) {
	return file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_rawDescGZIP(), []int{1}
}

type CaptureTheFlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag *Flag `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *CaptureTheFlagResponse) Reset() {
	*x = CaptureTheFlagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureTheFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureTheFlagResponse) ProtoMessage() {}

func (x *CaptureTheFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureTheFlagResponse.ProtoReflect.Descriptor instead.
func (*CaptureTheFlagResponse) Descriptor() ([]byte, []int) {
	return file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_rawDescGZIP(), []int{2}
}

func (x *CaptureTheFlagResponse) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

var File_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto protoreflect.FileDescriptor

var file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_rawDesc = []byte{
	0x0a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x73, 0x68,
	0x6c, 0x65, 0x79, 0x77, 0x61, 0x6e, 0x67, 0x31, 0x2f, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65,
	0x2d, 0x74, 0x68, 0x65, 0x2d, 0x66, 0x6c, 0x61, 0x67, 0x2d, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x77, 0x61, 0x6e, 0x67, 0x2e, 0x73,
	0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x1a, 0x12, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x04, 0x46, 0x6c,
	0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72,
	0x65, 0x54, 0x68, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x41, 0x0a, 0x16, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x54, 0x68, 0x65, 0x46, 0x6c, 0x61,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x66, 0x6c, 0x61,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x77, 0x61, 0x6e, 0x67, 0x2e,
	0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x32, 0x74, 0x0a, 0x11, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x54, 0x68, 0x65,
	0x46, 0x6c, 0x61, 0x67, 0x41, 0x70, 0x69, 0x12, 0x5f, 0x0a, 0x0e, 0x43, 0x61, 0x70, 0x74, 0x75,
	0x72, 0x65, 0x54, 0x68, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x24, 0x2e, 0x61, 0x77, 0x61, 0x6e,
	0x67, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72,
	0x65, 0x54, 0x68, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x61, 0x77, 0x61, 0x6e, 0x67, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e,
	0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x54, 0x68, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3f, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x73, 0x68, 0x6c, 0x65, 0x79, 0x77, 0x61, 0x6e,
	0x67, 0x31, 0x2f, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x2d, 0x74, 0x68, 0x65, 0x2d, 0x66,
	0x6c, 0x61, 0x67, 0x2d, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70,
	0x69, 0xc0, 0xf5, 0x04, 0x01, 0xb8, 0xf5, 0x04, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_rawDescOnce sync.Once
	file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_rawDescData = file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_rawDesc
)

func file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_rawDescGZIP() []byte {
	file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_rawDescOnce.Do(func() {
		file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_rawDescData)
	})
	return file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_rawDescData
}

var file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_goTypes = []interface{}{
	(*Flag)(nil),                   // 0: awang.solo.io.Flag
	(*CaptureTheFlagRequest)(nil),  // 1: awang.solo.io.CaptureTheFlagRequest
	(*CaptureTheFlagResponse)(nil), // 2: awang.solo.io.CaptureTheFlagResponse
}
var file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_depIdxs = []int32{
	0, // 0: awang.solo.io.CaptureTheFlagResponse.flag:type_name -> awang.solo.io.Flag
	1, // 1: awang.solo.io.CaptureTheFlagApi.CaptureTheFlag:input_type -> awang.solo.io.CaptureTheFlagRequest
	2, // 2: awang.solo.io.CaptureTheFlagApi.CaptureTheFlag:output_type -> awang.solo.io.CaptureTheFlagResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_init() }
func file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_init() {
	if File_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Flag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptureTheFlagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptureTheFlagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_goTypes,
		DependencyIndexes: file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_depIdxs,
		MessageInfos:      file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_msgTypes,
	}.Build()
	File_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto = out.File
	file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_rawDesc = nil
	file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_goTypes = nil
	file_github_com_ashleywang1_capture_the_flag_apiserver_api_apiserver_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CaptureTheFlagApiClient is the client API for CaptureTheFlagApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CaptureTheFlagApiClient interface {
	CaptureTheFlag(ctx context.Context, in *CaptureTheFlagRequest, opts ...grpc.CallOption) (*CaptureTheFlagResponse, error)
}

type captureTheFlagApiClient struct {
	cc grpc.ClientConnInterface
}

func NewCaptureTheFlagApiClient(cc grpc.ClientConnInterface) CaptureTheFlagApiClient {
	return &captureTheFlagApiClient{cc}
}

func (c *captureTheFlagApiClient) CaptureTheFlag(ctx context.Context, in *CaptureTheFlagRequest, opts ...grpc.CallOption) (*CaptureTheFlagResponse, error) {
	out := new(CaptureTheFlagResponse)
	err := c.cc.Invoke(ctx, "/awang.solo.io.CaptureTheFlagApi/CaptureTheFlag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaptureTheFlagApiServer is the server API for CaptureTheFlagApi service.
type CaptureTheFlagApiServer interface {
	CaptureTheFlag(context.Context, *CaptureTheFlagRequest) (*CaptureTheFlagResponse, error)
}

// UnimplementedCaptureTheFlagApiServer can be embedded to have forward compatible implementations.
type UnimplementedCaptureTheFlagApiServer struct {
}

func (*UnimplementedCaptureTheFlagApiServer) CaptureTheFlag(context.Context, *CaptureTheFlagRequest) (*CaptureTheFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CaptureTheFlag not implemented")
}

func RegisterCaptureTheFlagApiServer(s *grpc.Server, srv CaptureTheFlagApiServer) {
	s.RegisterService(&_CaptureTheFlagApi_serviceDesc, srv)
}

func _CaptureTheFlagApi_CaptureTheFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureTheFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureTheFlagApiServer).CaptureTheFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/awang.solo.io.CaptureTheFlagApi/CaptureTheFlag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureTheFlagApiServer).CaptureTheFlag(ctx, req.(*CaptureTheFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CaptureTheFlagApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "awang.solo.io.CaptureTheFlagApi",
	HandlerType: (*CaptureTheFlagApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CaptureTheFlag",
			Handler:    _CaptureTheFlagApi_CaptureTheFlag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/ashleywang1/capture-the-flag-apiserver/api/apiserver.proto",
}
